'use strict';

const randPrice = Math.floor(Math.random() * 1000).toFixed(2)

module.exports = {
  up: async (queryInterface, Sequelize) => {
    /**
     * Add seed commands here.
     *
     * Latin description : Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
     * see if you can write a function that can result in the location of the url of the image from aws-s3
     *
     * Example:
     */
    await queryInterface.bulkInsert('Shoes', [
      {sellerId:1, title:'Yeezy boost 350 V2 Bred', shoeSize:6,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-1.png" ,price:750.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:1, title:'Yeezy boost 350 V2 Beluga', shoeSize:13,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-2.png" ,price:440.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:1, title:'Yeezy Boost 350 V2 Zebra', shoeSize:8,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-3.png" ,price:500.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Yeezy boost 350 V2 Red', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-4.png" ,price:1205.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Yeezy boost 350 V2 Oreo ', shoeSize:7,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-5.png" ,price:375.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Yeezy boost 350 V2 Ycheil Non-Reflective ', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-6.png" ,price:1000.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Yeezy boost 350 V2 Semi Frozen Yellow ', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-7.png" ,price:1530.00,brand:"Yeezy" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Off-White x Air Jordan 1 Chicago ', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-8.png" ,price:280.00,brand:"Air Jordan" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Red Ribbon Recon x Air Jordan 1 Supreme & Louis Vuitton', shoeSize:13,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-9.png" ,price:425.00,brand:"Air Jordan" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Travis Scott x Air Jordan 1 Mocha ', shoeSize:13,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-10.png" ,price:240.00,brand:"Air Jordan" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Off-White x Air Jordan 1 UNC ', shoeSize:9,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-11.png" ,price:2250.00,brand:"Air Jordan" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Air Jordan 1 Royal 2013 ', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-12.png" ,price:1000.00,brand:"Air Jordan" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Gucci Ace Embroidered Snake ', shoeSize:7,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-13.png" ,price:350.00,brand:"Gucci" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Gucci Ace Embroidered Bee ', shoeSize:5,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-14.png" ,price:730.00,brand:"Gucci" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:3, title:'Gucci Ace GG Supreme Beige ', shoeSize:14,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-15.png" ,price:990.00,brand:"Gucci" , createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Gucci Rhython Leather Sneaker ', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-16.png" ,price:820.00,brand:"Gucci", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Gucci Pursuit 72 Rubber Slide Black', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-17.png" ,price:300.00,brand:"Gucci", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Gucci Wmns Stripe Rubber Slide Ecru', shoeSize:6,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-18.png" ,price:500.00,brand:"Gucci", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'New Balance Solebox White Mint 1500', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-19.png" ,price:245.00,brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'New Balance Solebox x 1500 Toothpaste Orange', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-20.png" ,price:255.00,brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Nike Dunk Low Grey Fog', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-21.png" ,price:200.00,brand:"Nike", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Nike Dunk Low Black White', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-22.png" ,price:250.00,brand:"Nike", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Nike Dunk Low Championship Red', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-23.png" ,price: 335.00,brand:"Nike", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Nike Social Status x Dunk Mid Chocolate Milk', shoeSize:12,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-24.png" ,price: 400.00,brand:"Nike", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Puma shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Puma shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Puma shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Reebok shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Reebok shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Reebok shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Vans shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Vans shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Vans shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Converse shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Converse shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Converse shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
      {sellerId:2, title:'Converse shoes', shoeSize:Math.floor(Math.random() * 14) + 2,description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.",image:"https://theplug-app-aws.s3.us-west-1.amazonaws.com/seed-25.png" ,price: Math.floor(Math.random() * 1901) + 100, brand:"New Balance", createdAt: new Date(), updatedAt:new Date()},
    ], {});
  },

  down: async (queryInterface, Sequelize) => {
    /**
     * Add commands to revert seed here.
     *
     * Example:
     */
    await queryInterface.bulkDelete('Shoes', null, {});
  }
};



//! Start uploading images into aws bucket then add url into the seeding key
